# Generated by Django 2.2.13 on 2020-10-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number_2',
        ),
    ]
