# Generated by Django 2.2.13 on 2020-10-04 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20201004_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_1',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name_1',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number_1',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number'),
        ),
    ]
